#!/bin/bash

echo 'WARNING: This will delete all temporary data generated by xigar. Do you want to continue? (y/n)'
read choice
if [ $choice == 'y' ]; then
	rm -rf *.out
	rm -rf *.mod
	rm -rf *.so
	rm -rf *.d
	rm -rf ./data/output/*
	rm -rf ./data/profiles/*
else
	exit 0
fi